
//! 123
//! Error
//! EXCEPTION! Test

import lib.libcore

try println(str(123)) with
    _ => println("Error")

fn test() {
    raise "error"
}

try test() with
    _ => println("Error")

try {
    raise "Test"
    ()
} with
    e => println("EXCEPTION! " + e)

